version: '3.4'

networks:
  my-network:
    driver: bridge

services:
  trolleyapi:
    image: ${DOCKER_REGISTRY-}trolleyapi
    build:
      context: .
      dockerfile: TrolleyAPI/Dockerfile
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=PA55W0RD
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/TrolleyAPI/https/aspnetapp.pfx
    ports:
        - "5000:80"
        - "5001:443"
    networks:
    - my-network
    volumes:
        - ./TrolleyAPI/https/aspnetapp.pfx:/TrolleyAPI/https/aspnetapp.pfx
    depends_on:
    - database

  database:
    container_name: db
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: TrolleyChoises
    ports: 
        - "5432:5432"
    networks:
        - my-network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
