version: '3.4'

networks:
  my-network:
    driver: bridge

services:
  trolleyapi:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          ASPNETCORE_URLS: https://+:80
    ports:
        - "5000:443"
    networks:
    - my-network
    depends_on:
    - database

  database:
    container_name: db
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: TrolleyChoises
    ports: 
        - "5432:5432"
    networks:
        - my-network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: